const state={endpoint:sessionStorage.getItem("umd_endpoint")||location.origin,key:sessionStorage.getItem("umd_key")||"",page:"overview",snapshot:null};
const $=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const titles={overview:["SYSTEM MAP","宇宙总览"],memories:["MEMORY ORBITS","记忆轨道"],retrieval:["GRAVITY LAB","引力调试"],graph:["CONSTELLATION MAP","星图关系"],entities:["IDENTITY GRAVITY","实体身份"],audit:["CHAIN OF CUSTODY","审计日志"]};
function toast(text){const el=$("#toast");el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
async function api(path,options={}){const response=await fetch(state.endpoint+path,{...options,headers:{Authorization:`Bearer ${state.key}`,"Content-Type":"application/json",...(options.headers||{})}});const payload=await response.json();if(!response.ok)throw new Error(payload.error?.message||`HTTP ${response.status}`);return payload}
function setConnected(ok,text){$("#healthDot").classList.toggle("ok",ok);$("#healthText").textContent=text}
async function connect(){const result=await api("/v1/system");state.snapshot=result.data;sessionStorage.setItem("umd_endpoint",state.endpoint);sessionStorage.setItem("umd_key",state.key);$("#connectModal").classList.remove("open");setConnected(true,"观测链路正常");render()}
$("#connectForm").addEventListener("submit",async e=>{e.preventDefault();state.endpoint=$("#endpoint").value.trim().replace(/\/$/,"")||location.origin;state.key=$("#apiKey").value.trim();$("#connectError").textContent="";try{await connect()}catch(err){$("#connectError").textContent=err.message}});
$("#endpoint").value=state.endpoint;$("#apiKey").value=state.key;
$("#disconnect").onclick=()=>{$("#connectModal").classList.add("open")};
$("#refresh").onclick=async()=>{try{state.snapshot=(await api("/v1/system")).data;await render();toast("观测数据已刷新")}catch(e){toast(e.message)}};
$("#navigation").addEventListener("click",e=>{const b=e.target.closest(".nav");if(!b)return;document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x===b));state.page=b.dataset.page;render()});
function shell(){const [eye,title]=titles[state.page];$("#pageEyebrow").textContent=eye;$("#pageTitle").textContent=title;$("#revisionBadge").textContent=`REV ${state.snapshot?.durable?.revision??"—"}`}
function stat(label,value,foot){return `<div class="card stat"><div class="stat-label">${esc(label)}</div><div class="stat-value">${esc(value)}</div><div class="stat-foot">${esc(foot)}</div></div>`}
async function overview(){const s=state.snapshot,d=s.durable,e=d.engine;const active=d.ram_active_nodes||0,total=d.records||0;$("#content").innerHTML=`<div class="grid stats">${stat("恒星主题",e.stars,"STAR SYSTEMS")}${stat("活跃记忆",active,`${total} TOTAL RECORDS`)}${stat("实体天体",s.active_entities,"CANONICAL ENTITIES")}${stat("时间轨道",s.temporal_orbits,"BITEMPORAL EDGES")}</div><div class="grid two-col"><div class="card"><div class="section-head"><h2>实时行星结构</h2><small>STAR → PLANET → MEMORY</small></div><div class="orbit-visual"><i class="sun"></i><i class="orbit-ring ring1"></i><i class="orbit-ring ring2"></i><i class="orbit-ring ring3"></i><i class="planet-dot p1"></i><i class="planet-dot p2"></i><i class="planet-dot p3"></i><i class="planet-dot p4"></i></div></div><div class="card"><div class="section-head"><h2>系统健康</h2><small>LIVE</small></div><div class="metric-list">${metric("事件链完整",d.event_chain_valid?100:0,d.event_chain_valid?"VALID":"INVALID")}${metric("活跃容量",100*active/Math.max(1,e.active_memories||active),`${active}`)}${metric("索引记忆",100*Math.min(1,(s.ann_indexed_memories||0)/Math.max(1,active)),s.ann_indexed_memories||0)}${metric("实体置信",s.identity_ambiguities?75:100,s.identity_ambiguities?`${s.identity_ambiguities} 待确认`:"CLEAR")}</div></div></div>`}
function metric(name,pct,value){return `<div class="metric-row"><span>${esc(name)}</span><div class="bar"><i style="width:${Math.max(0,Math.min(100,pct))}%"></i></div><b>${esc(value)}</b></div>`}
async function memories(){const payload=await api("/v1/memories?limit=100");const rows=payload.data.map(m=>`<tr><td><span class="pill ${esc(m.state)}">${esc(m.state)}</span></td><td class="memory-text">${esc(m.text)}</td><td>${esc(m.scope||"—")}</td><td>${esc(m.entities.slice(0,3).join(", ")||"—")}</td><td>${esc(m.updated_at.slice(0,16).replace("T"," "))}</td></tr>`).join("");$("#content").innerHTML=`<div class="toolbar"><input id="memoryFilter" placeholder="过滤记忆文本、作用域或实体"><select id="stateFilter"><option value="">全部状态</option><option>stable</option><option>provisional</option><option>archived</option></select><button id="newMemory" class="primary">＋ 新建记忆</button></div><div class="card"><table><thead><tr><th>状态</th><th>记忆</th><th>作用域</th><th>实体</th><th>更新时间</th></tr></thead><tbody id="memoryRows">${rows||'<tr><td colspan="5" class="empty">没有记忆</td></tr>'}</tbody></table></div>`;const filter=()=>{const q=$("#memoryFilter").value.toLowerCase(),st=$("#stateFilter").value;document.querySelectorAll("#memoryRows tr").forEach(row=>row.hidden=!(row.textContent.toLowerCase().includes(q)&&(!st||row.querySelector(".pill")?.textContent===st)))};$("#memoryFilter").oninput=filter;$("#stateFilter").onchange=filter;$("#newMemory").onclick=()=>$("#memoryDialog").showModal()}
async function retrieval(){$("#content").innerHTML=`<div class="card"><div class="section-head"><h2>查询彗星</h2><small>ADAPTIVE FORCE DECOMPOSITION</small></div><form id="searchForm" class="toolbar"><input id="query" placeholder="输入问题，观察每个引力分量……" required><button class="primary">发射查询</button></form><div id="searchResults" class="retrieval-results"><div class="empty">等待查询进入行星系</div></div></div>`;$("#searchForm").onsubmit=async e=>{e.preventDefault();const q=$("#query").value;const out=$("#searchResults");out.innerHTML='<div class="empty">计算引力轨迹…</div>';try{const hits=(await api("/v1/search",{method:"POST",body:JSON.stringify({query:q,top_k:8})})).data;out.innerHTML=hits.map(h=>hitCard(h)).join("")||'<div class="empty">没有捕获到记忆</div>'}catch(err){out.innerHTML=`<div class="empty">${esc(err.message)}</div>`}}}
function hitCard(h){const keys=["semantic_gravity","bm25_resonance","entity_resonance","temporal_phase","graph_flux","neural_rerank","contradiction_repulsion"];return `<article class="hit"><div class="force">${h.force.toFixed(3)}<small>FORCE</small></div><div><p>${esc(h.text)}</p><div class="component-bars">${keys.map(k=>`<div class="component">${esc(k.replaceAll("_"," "))}<div class="bar"><i style="width:${100*Math.min(1,h.components[k]||0)}%"></i></div></div>`).join("")}</div></div></article>`}
async function graph(){const data=(await api("/v1/graph?limit=700")).data;$("#content").innerHTML='<div class="card graph-wrap"><svg id="starGraph" viewBox="0 0 1100 610"></svg></div>';drawGraph(data)}
function drawGraph(data){const svg=$("#starGraph"),NS="http://www.w3.org/2000/svg",nodes=data.nodes.slice(0,260),map=new Map();const colors={star:"#ffe28a",planet:"#5de4ff",memory:"#5a7cff",entity:"#a875ff"};nodes.forEach((n,i)=>{const angle=i*2.399963,r=38+Math.sqrt(i)*30;n.x=550+Math.cos(angle)*Math.min(r,500);n.y=305+Math.sin(angle)*Math.min(r*.56,275);map.set(n.id,n)});data.edges.slice(0,600).forEach(e=>{const a=map.get(e.source),b=map.get(e.target);if(!a||!b)return;const line=document.createElementNS(NS,"line");line.setAttribute("x1",a.x);line.setAttribute("y1",a.y);line.setAttribute("x2",b.x);line.setAttribute("y2",b.y);line.setAttribute("stroke","#263c57");line.setAttribute("stroke-width",Math.max(.4,(e.confidence||.3)*1.4));svg.append(line)});nodes.forEach(n=>{const c=document.createElementNS(NS,"circle");c.setAttribute("cx",n.x);c.setAttribute("cy",n.y);c.setAttribute("r",n.type==="star"?9:n.type==="planet"?6:3.5);c.setAttribute("fill",colors[n.type]||"#fff");c.setAttribute("opacity",n.type==="memory"?.72:1);const title=document.createElementNS(NS,"title");title.textContent=`${n.type}: ${n.label}`;c.append(title);svg.append(c);if(n.type!=="memory"){const t=document.createElementNS(NS,"text");t.setAttribute("x",n.x+9);t.setAttribute("y",n.y+3);t.setAttribute("class","node-label");t.textContent=String(n.label).slice(0,22);svg.append(t)}})}
async function entities(){const [entities,ambiguities]=await Promise.all([api("/v1/entities"),api("/v1/ambiguities")]);const rows=entities.data.map(e=>`<tr><td>${esc(e.canonical_name)}</td><td><span class="pill">${esc(e.entity_type)}</span></td><td>${Number(e.confidence).toFixed(2)}</td><td>${esc((e.aliases||[]).join(", "))}</td></tr>`).join("");$("#content").innerHTML=`<div class="grid stats">${stat("规范实体",entities.data.length,"CANONICAL")}${stat("身份歧义",ambiguities.data.length,"QUARANTINED")}${stat("自动合并",entities.data.filter(e=>(e.aliases||[]).length>1).length,"ALIASED")}${stat("待审核",ambiguities.data.length,"IDENTITY MARGIN")}</div><div class="card"><table><thead><tr><th>规范名称</th><th>类型</th><th>置信度</th><th>别名</th></tr></thead><tbody>${rows||'<tr><td colspan="4" class="empty">暂无实体</td></tr>'}</tbody></table></div>`}
async function audit(){const events=(await api("/v1/audit?limit=200")).data;const rows=events.map(e=>`<tr><td><span class="pill">${e.revision}</span></td><td>${esc(e.event_type)}</td><td>${esc(e.aggregate_id||"—")}</td><td><code>${esc(e.event_hash.slice(0,14))}…</code></td><td>${esc(e.created_at.slice(0,19).replace("T"," "))}</td></tr>`).join("");$("#content").innerHTML=`<div class="card"><div class="section-head"><h2>加密事件链</h2><small>${events.length} RECENT EVENTS</small></div><table><thead><tr><th>版本</th><th>事件</th><th>聚合对象</th><th>链哈希</th><th>时间</th></tr></thead><tbody>${rows}</tbody></table></div>`}
async function render(){shell();const pages={overview,memories,retrieval,graph,entities,audit};try{await pages[state.page]()}catch(err){$("#content").innerHTML=`<div class="card empty">${esc(err.message)}</div>`;setConnected(false,"观测异常")}}
if(state.key)connect().catch(()=>$("#connectModal").classList.add("open"));
$("#cancelMemory").onclick=()=>$("#memoryDialog").close();
$("#memoryForm").onsubmit=async e=>{e.preventDefault();$("#memoryError").textContent="";try{await api("/v1/memories",{method:"POST",headers:{"Idempotency-Key":`console-${crypto.randomUUID()}`},body:JSON.stringify({text:$("#newText").value,scope:$("#newScope").value||null,importance:Number($("#newImportance").value),tags:$("#newTags").value.split(",").map(x=>x.trim()).filter(Boolean)})});$("#memoryDialog").close();e.target.reset();toast("记忆已封装并进入轨道");state.snapshot=(await api("/v1/system")).data;render()}catch(err){$("#memoryError").textContent=err.message}};
